[pytest]
python_files = *utils.py
markers = 
capitalize_test_pozitive: проверка заглавной буквы поз, capitalize_test_negative: проверка заглавных букв нег,
trim_test_pozitive: проверка удаления пробелов полож, trim_test_negative: проверка удаления пробелов негатив
search_symbol_pozitive: поиск символа в слове поз
search_symbol_negative: поиск символа нег
delete_symbol_pozitive: проверка удаления символа поз
delete_symbol_negative: проверка удаления символа нег  
delete_none: удаление ничего